#pragma once
// generated by export_model.py -- do not edit

static const int   MODEL_N_FEATURES = 31;
static const int   MODEL_N_CLASSES  = 9;

static const char* CLASS_NAMES[] = {
    "normal",
    "ransomware",
    "thetick",
    "bashlite",
    "httpbackdoor",
    "beurk",
    "backdoor",
    "bdvl",
    "xmrig",
};

// The collector MUST fill the input vector in exactly this order.
static const char* FEATURE_ORDER[] = {
    "madvise",
    "setgroups32",
    "statfs64",
    "seconds_RES_data",
    "getsockname",
    "connect",
    "block:block_unplug_KERN_data",
    "ext4:ext4_ext_rm_leaf",
    "socket",
    "jbd2:jbd2_handle_extend",
    "util",
    "write_kbs",
    "rename",
    "prlimit64",
    "write_merge",
    "dup2",
    "recv",
    "ext4:ext4_da_update_reserve_space_RES_data",
    "iowrite",
    "fchmod",
    "setitimer",
    "mkdir",
    "inotify_add_watch",
    "ext4:ext4_ext_remove_space_done",
    "pipe2",
    "writeback:sb_clear_inode_writeback_KERN_data",
    "brk",
    "shutdown",
    "getegid32",
    "iowritetime",
    "geteuid32",
};
